// Code generated by xgoja; DO NOT EDIT.
package main

import (
	"embed"
	"encoding/json"
	"fmt"
	"os"

	geppetto "github.com/go-go-golems/geppetto/pkg/js/modules/geppetto/provider"
	"github.com/go-go-golems/go-go-goja/pkg/xgoja/app"
	"github.com/go-go-golems/go-go-goja/pkg/xgoja/providerapi"
	go_go_goja_core "github.com/go-go-golems/go-go-goja/pkg/xgoja/providers/core"
	go_go_goja_host "github.com/go-go-golems/go-go-goja/pkg/xgoja/providers/host"
	goja_bleve "github.com/go-go-golems/goja-bleve/pkg/xgoja/providers/bleve"
)

const embeddedSpecJSON = `{
  "name": "goja-bleve-vectors",
  "appName": "goja-bleve",
  "target": {
    "kind": "xgoja",
    "output": "dist/goja-bleve-vectors"
  },
  "packages": [
    {
      "id": "goja-bleve",
      "import": "github.com/go-go-golems/goja-bleve/pkg/xgoja/providers/bleve",
      "version": "v0.0.0",
      "register": "Register",
      "replace": "../.."
    },
    {
      "id": "geppetto",
      "import": "github.com/go-go-golems/geppetto/pkg/js/modules/geppetto/provider",
      "version": "v0.0.0",
      "register": "Register",
      "replace": "../../../geppetto"
    },
    {
      "id": "go-go-goja-core",
      "import": "github.com/go-go-golems/go-go-goja/pkg/xgoja/providers/core",
      "register": "Register",
      "replace": "../../../go-go-goja"
    },
    {
      "id": "go-go-goja-host",
      "import": "github.com/go-go-golems/go-go-goja/pkg/xgoja/providers/host",
      "register": "Register",
      "replace": "../../../go-go-goja"
    }
  ],
  "modules": [
    {
      "package": "goja-bleve",
      "name": "bleve",
      "as": "bleve"
    },
    {
      "package": "geppetto",
      "name": "geppetto",
      "as": "geppetto"
    },
    {
      "package": "go-go-goja-core",
      "name": "path",
      "as": "path"
    },
    {
      "package": "go-go-goja-core",
      "name": "yaml",
      "as": "yaml"
    },
    {
      "package": "go-go-goja-host",
      "name": "fs",
      "as": "fs",
      "config": {
        "allow": true
      }
    }
  ],
  "commands": {
    "eval": {
      "enabled": true,
      "name": "eval"
    },
    "run": {
      "enabled": true,
      "name": "run"
    },
    "repl": {
      "enabled": true,
      "name": "repl"
    },
    "jsverbs": {
      "enabled": true,
      "name": "verbs",
      "mount": "root"
    }
  },
  "jsverbs": [
    {
      "id": "goja-bleve-bundled-verbs",
      "path": "xgoja_embed/jsverbs/goja_bleve_bundled_verbs",
      "embed": true
    }
  ],
  "help": {
    "sources": [
      {
        "id": "goja-bleve-docs",
        "path": "help",
        "embed": true
      }
    ]
  }
}
`

//go:embed xgoja_embed/jsverbs/*
var embeddedJSVerbs embed.FS

//go:embed help/topics/*.md help/tutorials/*.md
var embeddedHelp embed.FS

func main() {
	registry := providerapi.NewProviderRegistry()
	must(goja_bleve.Register(registry))
	must(geppetto.Register(registry))
	must(go_go_goja_core.Register(registry))
	must(go_go_goja_host.Register(registry))
	root, err := app.NewRootCommand(app.Options{Providers: registry, SpecJSON: embeddedSpecJSON, EmbeddedJSVerbs: embeddedJSVerbs, EmbeddedHelp: embeddedHelp, EmbeddedAssets: nil})
	must(err)
	if err := root.Execute(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func decodeSpec() *app.RuntimeSpec {
	buildSpec := &app.RuntimeSpec{}
	must(json.Unmarshal([]byte(embeddedSpecJSON), buildSpec))
	return buildSpec
}

func must(err error) {
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
