// Code generated by logcopter-gen; DO NOT EDIT.

package bleve

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var log = logcopter.Package("go-go-golems.goja_bleve.pkg.xgoja.providers.bleve")
